// ==============================================================================
// ELVAVEO Sales Agent - Initial State & Seed Data
// ==============================================================================

import { Lead, EmailDraft, DraftApproval, SendLog, Suppression, AuditLog } from './types/database';
import { ELVAVEO_EMAIL_IDENTITY } from './email/identity';
import { computeContentHash } from './personalization/template';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    workspace_id: 'ws-default',
    email: 'sarah.connor@cyberdyne-sys.com',
    first_name: 'Sarah',
    last_name: 'Connor',
    company: 'Cyberdyne Systems',
    role: 'Head of Infrastructure',
    website: 'https://cyberdyne-sys.com',
    source: 'inbound_form',
    notes: 'Requested product whitepaper on high-throughput compute.',
    consent_status: 'opted_in',
    consent_source: 'web_form_consent_checkbox',
    consent_timestamp: '2026-10-02T14:32:00Z',
    status: 'new',
    country: 'USA',
    target_service: 'custom_saas',
    source_url: 'https://cyberdyne-sys.com/infrastructure',
    researched_at: '2026-10-02T14:32:00Z',
    business_observations: [
      'Customer dashboard uses monolithic session cookies without RESTful tenant tokenization.',
      'API documentation indicates manual provisioning rather than multi-tenant automated provisioning.',
    ],
    confidence_level: 'high',
    permission_type: 'verified_opt_in',
    lifecycle_stage: 'qualified',
    created_at: '2026-10-02T14:32:00Z',
    updated_at: '2026-10-02T14:32:00Z',
  },
  {
    id: 'lead-2',
    workspace_id: 'ws-default',
    email: 'marcus.vance@vanguard-tech.io',
    first_name: 'Marcus',
    last_name: 'Vance',
    company: 'Vanguard Technologies',
    role: 'VP Engineering',
    website: 'https://vanguard-tech.io',
    source: 'partner_referral',
    notes: 'Met at Cloud Expo Austin.',
    consent_status: 'opted_in',
    consent_source: 'verbal_partner_intro',
    consent_timestamp: '2026-10-03T09:15:00Z',
    status: 'new',
    country: 'UK',
    target_service: 'crm_development',
    source_url: 'https://vanguard-tech.io',
    researched_at: '2026-10-03T09:15:00Z',
    business_observations: [
      'Contact forms submit to generic mailto handler with no automated CRM lead capture.',
      'No webhook-based lead qualification pipeline detected in frontend asset bundles.',
    ],
    confidence_level: 'high',
    permission_type: 'verified_opt_in',
    lifecycle_stage: 'qualified',
    created_at: '2026-10-03T09:15:00Z',
    updated_at: '2026-10-03T09:15:00Z',
  },
  {
    id: 'lead-3',
    workspace_id: 'ws-default',
    email: 'elena.rostova@hyperion-labs.net',
    first_name: 'Elena',
    last_name: 'Rostova',
    company: 'Hyperion Labs',
    role: 'Chief Technology Officer',
    website: 'https://hyperion-labs.net',
    source: 'ai_discovery_engine',
    notes: 'Identified via technical directory. Public web portal runs legacy WordPress with non-responsive layout.',
    consent_status: 'unknown', // STRICT DEFAULT!
    consent_source: null,
    consent_timestamp: null,
    status: 'new',
    country: 'UAE',
    target_service: 'website_development',
    source_url: 'https://hyperion-labs.net',
    researched_at: '2026-10-04T11:00:00Z',
    business_observations: [
      'Public web portal runs legacy CMS with non-responsive table layouts on mobile viewports.',
      'Google Lighthouse audit reports 42/100 Mobile Performance due to uncompressed hero assets.',
    ],
    confidence_level: 'high',
    permission_type: 'unknown',
    lifecycle_stage: 'discovered',
    created_at: '2026-10-04T11:00:00Z',
    updated_at: '2026-10-04T11:00:00Z',
  },
  {
    id: 'lead-4',
    workspace_id: 'ws-default',
    email: 'david.chen@solaris-energy.com',
    first_name: 'David',
    last_name: 'Chen',
    company: 'Solaris Energy',
    role: 'Director of Operations',
    website: 'https://solaris-energy.com',
    source: 'conference_contact',
    notes: 'Requested no further outreach.',
    consent_status: 'opted_out',
    consent_source: 'email_reply',
    consent_timestamp: '2026-10-05T16:20:00Z',
    status: 'do_not_contact',
    country: 'Canada',
    target_service: 'crm_development',
    source_url: 'https://solaris-energy.com',
    researched_at: '2026-10-05T16:20:00Z',
    business_observations: [
      'Inquiry forms lack CRM pipeline automation, routing exclusively to static info@ inbox.',
    ],
    confidence_level: 'medium',
    permission_type: 'unknown',
    lifecycle_stage: 'suppressed',
    created_at: '2026-10-05T16:20:00Z',
    updated_at: '2026-10-05T16:20:00Z',
  },
];

export const INITIAL_SUPPRESSIONS: Suppression[] = [
  {
    id: 'supp-1',
    workspace_id: 'ws-default',
    email: 'david.chen@solaris-energy.com',
    reason: 'unsubscribe',
    source_details: 'Direct opt-out request via reply',
    created_at: '2026-10-05T16:20:00Z',
  },
  {
    id: 'supp-2',
    workspace_id: 'ws-default',
    email: 'bounced.prospect@olddomain-inactive.org',
    reason: 'bounce',
    source_details: 'Permanent hard bounce received from Resend webhook',
    created_at: '2026-10-01T10:00:00Z',
  },
];

const sampleFooterText =
  '---\nELVAVEO\nTo unsubscribe: https://outreach.elvaveo.com/unsubscribe?token=sample';
const sampleFooterHtml =
  '<div style="margin-top:24px;border-top:1px solid #e5e7eb;padding-top:12px;font-size:12px;color:#6b7280;"><p style="font-weight:600;margin:0 0 4px 0;color:#374151;">ELVAVEO</p></div>';

const hash1 = computeContentHash({
  recipientEmail: INITIAL_LEADS[0].email,
  senderEmail: ELVAVEO_EMAIL_IDENTITY.SENDER,
  replyToEmail: ELVAVEO_EMAIL_IDENTITY.REPLY_TO,
  subject: 'Accelerating Infrastructure Automation for Cyberdyne Systems',
  bodyText: 'Hi Sarah,\n\nWe saw your recent paper on scalable infrastructure. Would you have 15 minutes to discuss automation?',
  bodyHtml: '<p>Hi Sarah,</p><p>We saw your recent paper on scalable infrastructure. Would you have 15 minutes to discuss automation?</p>',
  footerText: sampleFooterText,
  footerHtml: sampleFooterHtml,
});

export const INITIAL_DRAFTS: EmailDraft[] = [
  {
    id: 'draft-approved-1',
    workspace_id: 'ws-default',
    lead_id: INITIAL_LEADS[0].id,
    template_id: null,
    version: 1,
    recipient_email: INITIAL_LEADS[0].email,
    sender_email: ELVAVEO_EMAIL_IDENTITY.SENDER,
    reply_to_email: ELVAVEO_EMAIL_IDENTITY.REPLY_TO,
    subject: 'Accelerating Infrastructure Automation for Cyberdyne Systems',
    body_text: 'Hi Sarah,\n\nWe saw your recent paper on scalable infrastructure. Would you have 15 minutes to discuss automation?',
    body_html: '<p>Hi Sarah,</p><p>We saw your recent paper on scalable infrastructure. Would you have 15 minutes to discuss automation?</p>',
    footer_text: sampleFooterText,
    footer_html: sampleFooterHtml,
    content_hash: hash1,
    status: 'approved',
    missing_fields: [],
    created_by: 'operator-1',
    created_at: '2026-10-06T10:00:00Z',
    updated_at: '2026-10-06T11:00:00Z',
  },
  {
    id: 'draft-pending-2',
    workspace_id: 'ws-default',
    lead_id: INITIAL_LEADS[1].id,
    template_id: null,
    version: 1,
    recipient_email: INITIAL_LEADS[1].email,
    sender_email: ELVAVEO_EMAIL_IDENTITY.SENDER,
    reply_to_email: ELVAVEO_EMAIL_IDENTITY.REPLY_TO,
    subject: 'Engineering Sales Productivity at Vanguard Technologies',
    body_text: 'Hi Marcus,\n\nGreat connecting at Cloud Expo Austin. We are helping engineering teams streamline sales workflows.',
    body_html: '<p>Hi Marcus,</p><p>Great connecting at Cloud Expo Austin. We are helping engineering teams streamline sales workflows.</p>',
    footer_text: sampleFooterText,
    footer_html: sampleFooterHtml,
    content_hash: 'hash-pending-2',
    status: 'pending_review',
    missing_fields: [],
    created_by: 'operator-1',
    created_at: '2026-10-07T14:00:00Z',
    updated_at: '2026-10-07T14:00:00Z',
  },
];

export const INITIAL_APPROVALS: DraftApproval[] = [
  {
    id: 'appr-1',
    workspace_id: 'ws-default',
    draft_id: 'draft-approved-1',
    draft_version: 1,
    content_hash: hash1,
    approved_by: 'reviewer-admin',
    decision: 'approved',
    comment: 'Checked and verified affirmative consent recorded.',
    created_at: '2026-10-06T11:00:00Z',
  },
];

export const INITIAL_SEND_LOGS: SendLog[] = [
  {
    id: 'send-log-1',
    workspace_id: 'ws-default',
    draft_id: 'draft-prev-test',
    lead_id: 'lead-test-demo',
    recipient_email: 'operator-test@elvaveo.com',
    send_mode: 'test',
    is_test: true,
    idempotency_key: 'idemp-test-sample-001',
    provider: 'resend',
    resend_email_id: 're_sample_test_email_001',
    status: 'delivered',
    error_message: null,
    sent_by: 'reviewer-admin',
    sent_at: '2026-10-07T16:30:00Z',
    updated_at: '2026-10-07T16:31:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    workspace_id: 'ws-default',
    actor_id: 'admin-user',
    actor_email: 'admin@elvaveo.com',
    action: 'workspace:initialized',
    entity_type: 'workspace',
    entity_id: 'ws-default',
    details: { dailyLimit: 50, hourlyLimit: 10, mode: 'test' },
    created_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'audit-2',
    workspace_id: 'ws-default',
    actor_id: 'operator-1',
    actor_email: 'operator@elvaveo.com',
    action: 'lead:created',
    entity_type: 'lead',
    entity_id: 'lead-1',
    details: { email: 'sarah.connor@cyberdyne-sys.com', consent: 'opted_in' },
    created_at: '2026-10-02T14:32:00Z',
  },
  {
    id: 'audit-3',
    workspace_id: 'ws-default',
    actor_id: 'reviewer-admin',
    actor_email: 'reviewer@elvaveo.com',
    action: 'draft:approved',
    entity_type: 'approval',
    entity_id: 'draft-approved-1',
    details: { version: 1, decision: 'approved' },
    created_at: '2026-10-06T11:00:00Z',
  },
];
